"""empty message

Revision ID: 57a9f62db054
Revises: None
Create Date: 2016-12-01 15:59:25.794106

"""

# revision identifiers, used by Alembic.
revision = '57a9f62db054'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
